### PR TITLE
update mutligpu readme and MllamaForConditionalGeneration import

### LINKED ISSUE #680: Incorrect import in version 0.0.4
### System Info

PyTorch 2.4.0, CUDA 12.1, 7x H100

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

Import of `MllamaForConditionalGeneration` on https://github.com/meta-llama/llama-recipes/blob/main/src/llama_recipes/finetuning.py#L24 should be on line 28 instead. It is part of mllama module, not main transformers library

### Error logs

Throws import error

### Expected behavior

Have fixed this in https://github.com/AAndersn/llama-recipes/blob/main/src/llama_recipes/finetuning.py#L27. Will make PR to fix it along with int4 -> 4 bit fix in readme

### PR DESCRIPTION
**Pull request by AAndersn**
Fixes an incorrect parameter in documentation for multigpu that says `int4` instead of `4bit` for quantization type.

Fixes incorrect import of MllamaForConditionalGeneration from `transformers` instead of `transformers.models.mllama.modeling_mllama`

Fixes #680 

## Before submitting
- [ X] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ X] Did you read the [contributor guideline](https://github.com/facebookresearch/llama-recipes/blob/main/CONTRIBUTING.md#pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue? Please add a link
      to it if that's the case.
- [ X] Did you make sure to update the documentation with your changes?  
- [ ] Did you write any new necessary tests?

Thanks for contributing 🎉!

### CODE REVIEW

**Comment by AAndersn** [comment]
@wukaixingxp You are right. 

I think I might have had the 4.44.0 when I created that bug ticket and PR last night. Re-running with transformers 4.45.0 this morning and `from transformers import MllamaForConditionalGeneration` works fine

**Comment by wukaixingxp** [comment]
Thanks for your help! We want to bump the transformer version to 4.45.0 but it has a bug as stated in [my PR](https://github.com/meta-llama/llama-recipes/pull/686). Now people must pip install from source for transformers to avoid this bug. We are waiting for a new release of transformers pip package.

**Comment by init27** [comment]
@AAndersn thanks again for the PR-since this is fixed in the latest HF version can you take another parse please?

**Comment by AAndersn** [comment]
Sorry for the delay. Yes, I will fix my branch to resolve the conflict with the other portion that has already been fixed

**Pull request closed without merging**
