### PR TITLE
Add Llama2 + EC2 tutorial using Runhouse

### PR DESCRIPTION
**Pull request by rohinb2**
A simple code file to stand up a Llama2 model on an A10G running in EC2. Uses the Runhouse Python library to easily provision an instance, copy code over, and serve the model.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/facebookresearch/llama-recipes/blob/main/CONTRIBUTING.md#pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes?  
- [ ] Did you write any new necessary tests?

Thanks for contributing 🎉!

### CODE REVIEW

**Comment by rohinb2** [comment]
cc: @HamidShojanazeri @mreso 

Sorry to tag, not sure who to request for review here.

**Comment by dongreenberg** [comment]
Also adding in @subramen , with whom we've previously discussed this example.

**Comment by HamidShojanazeri** [comment]
Thanks @rohinb2 for the PR will sync up with Suraj and review.

**Comment by rohinb2** [comment]
Hi @HamidShojanazeri, I made a new [PR](https://github.com/meta-llama/llama-recipes/pull/431) for the new format.

**Pull request closed without merging**
