### PR TITLE
added instructions in README.md for proper multi modal inferencing with Llama 3.2 models

### PR DESCRIPTION
**Pull request by himanshushukla12**
# What does this PR do?

Previously, I addressed the fix for the [multi-modal inferencing issue](https://github.com/meta-llama/llama-recipes/pull/704), but I didn't include additional information in the `README.md`. 

I have now made those changes to make it easier for readers to use the latest ` Llama 3.2 vision models `.

## Before submitting
- [x] This PR fixes a typo or improves the documentation (you can dismiss the other checks if that's the case).

### CODE REVIEW

**Comment by himanshushukla12** [comment]
> Thanks for the PR-can you instead please update the `requirements.txt` for the main project?

I'll do that, so should I discard these changes? and do i only modify the `requirements.txt`

or `README.md` and `requirements.txt` both?

**Comment by himanshushukla12** [comment]
@init27 The `requirements.txt` is already in good shape

**Comment by init27** [comment]
Ok in that case, I will close the PR. 

The expected flow would be-you should run/install the `llama-recipes` package/repo and then run the examples. 

Please let me know if you have any thoughts

**Comment by himanshushukla12** [comment]
@init27 Should I add a gradio/Streamlit UI interface for this llama3.2 ??

Or if you have any suggestions please let me know

**Comment by init27** [comment]
@himanshushukla12 Yeah a simple app would be a cool idea-thanks for suggesting! 

Quick Note: 11B and 90B both support single-image at the time (you cannot change to different image later either)

Let me know if you need help with any Qs!

**Comment by himanshushukla12** [comment]
@init27 So should I start working to push simple gradio app then later on I'll make it completely chat like interface?

**Comment by himanshushukla12** [comment]
@init27 I'm interested in contribution to this repo so trying to come up with ideas...

**Comment by init27** [comment]
Thank you, appreciate your interest! 

Yeah a gradio app with all the HF params for inference would be a great contribution!

**Comment by himanshushukla12** [comment]
@init27 just give me 24 hours of time, I'll raise Pull request after completing the UI work.

**Comment by init27** [comment]
Feel free to ask for help!

**Pull request closed without merging**
