### PR TITLE
Fix version number in Python example

### PR DESCRIPTION
**Pull request by wstnmssr**
# What does this PR do?

Replace `llama3` with `llama3.1`  in code example to avoid model not found error.

## Feature/Issue validation/testing

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

To reproduce the error, copy and paste the sample python code. The response is `{'error': 'model "llama3" not found, try pulling it first'}`.

This fix was tested manually by observing a proper, non-error response when using the appropriate version number.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/facebookresearch/llama-recipes/blob/main/CONTRIBUTING.md#pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes?  
- [ ] Did you write any new necessary tests?

Thanks for contributing 🎉!

### CODE REVIEW

**Comment by init27** [comment]
Thanks @wstnmssr can you please sign the CLA?

**Comment by wstnmssr** [comment]
> Thanks @wstnmssr can you please sign the CLA?

Hey @init27, I tried to do this but after submitting the form, I was not able to authenticate with my GitHub account. Upon submitting, I was taken to `https://code.facebook.com/cla/individual/sign/`, which was just a blank page.

**Comment by init27** [comment]
@wstnmssr Can you try with `https://code.facebook.com/cla/individual` link? 

You should be checking at `https://code.facebook.com/cla`

Let me know if you run into any issues

**Comment by wstnmssr** [comment]
@init27 That's the link I've been using, and I'm running into the same issue I described earlier. When I am redirected to the URL I mentioned, this is all I see: 
image

**Comment by init27** [comment]
That's strange-can you try the same with a different browser please?

**Comment by wstnmssr** [comment]
> That's strange-can you try the same with a different browser please?

Looks like it works in safari. I agree, odd that it is not working for me in chrome.

**Review by init27 — APPROVED** [review]

**Pull request merged**
