### PR TITLE
[OctoAI] Llama-3 based summarization + RAG to power a sales bot

### PR DESCRIPTION
**Pull request by tmoreau89**
# What does this PR do?

Introducing a new Llama3 example that is built on top of OctoAI model API provider and Weaviate vector DB to implement a helpful sales bot.

Example interaction:

User: "what is must have accessory for my new electric guitar"

Chatbot: 
> Congratulations on your new electric guitar! 
> A must-have accessory for your new electric guitar is a good case to protect it from damage and scratches. I highly recommend the [Solid Electric Guitar Case with Accessories Compartment](https://www.amazon.com/exec/obidos/ASIN/B00A270KYM). This case provides good protection and has a roomy accessories compartment to store your guitar's accessories. 
> Another great option is the [Hard Guitar Case with Accessory Compartments](https://www.amazon.com/exec/obidos/ASIN/B001FB5Z44), which is sturdy and has additional compartments for accessories. 
> If you're looking for a more affordable option, the [Affordable Solid Body Electric Guitar Case](https://www.amazon.com/exec/obidos/ASIN/B000CDT4VQ) is a great choice. It's well-built, durable, and fits various solid body electric guitars.
> References:
[1] [Solid Electric Guitar Case with Accessories Compartment](https://www.amazon.com/exec/obidos/ASIN/B00A270KYM)
[2] [Hard Guitar Case with Accessory Compartments](https://www.amazon.com/exec/obidos/ASIN/B001FB5Z44)
[3] [Affordable Solid Body Electric Guitar Case](https://www.amazon.com/exec/obidos/ASIN/B000CDT4VQ)

## Feature/Issue validation/testing
Ran on a local jupyter notebook on Macbook M1.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/facebookresearch/llama-recipes/blob/main/CONTRIBUTING.md#pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes?  
- [ ] Did you write any new necessary tests?

Thanks for contributing 🎉!

### CODE REVIEW

**Comment by tmoreau89** [comment]
CC @HamidShojanazeri

**Review by HamidShojanazeri — APPROVED** [review]
Thanks @tmoreau89 for the PR!

**Comment by tmoreau89** [comment]
@HamidShojanazeri we're all green here 🙌

**Review by HamidShojanazeri — APPROVED** [review]

**Comment by tmoreau89** [comment]
Merge conflicts resolved!

**Pull request merged**
