### PR TITLE
Add Groq/Llama3 recipes (cookbook and command line examples)

### PR DESCRIPTION
**Pull request by dloman118**
# What does this PR do?

## Feature/Issue validation/testing

These cookbooks can be run as jupyter notebooks provided that `GROQ_API_KEY` is set as an environment variable (Groq API Keys can be curated here: https://console.groq.com/keys

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/facebookresearch/llama-recipes/blob/main/CONTRIBUTING.md#pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes?  
- [ ] Did you write any new necessary tests?

Thanks for contributing 🎉!

6/6 update: I am failing on lint/spellcheck tests but I don't believe that I should be:
- https://console.groq.com/keys is a valid address (you do need to be logged in)
- Words such as 'Groq', 'GroqCloud', 'DuckDB' and 'Replit' are valid in the context of my README files

### CODE REVIEW

**Comment by HamidShojanazeri** [comment]
@dloman118 thanks for the PR! can we pls merge all the Groq examples under Groq folder? `recipes/
/llama_api_providers/Groq`  that would help with a cleaner outline.

**Comment by HamidShojanazeri** [comment]
Also appreciate if we can fix the broken link errors.

**Comment by dloman118** [comment]
@HamidShojanazeri thanks for reviewing! I made a new commit to move all of the Groq examples to a new Groq folder (I left `llama3_cookbook_groq.ipynb `separate within that folder because it was not authored by us, but could move it with the other cookbook posts if that is preferable). I had removed one broken link, but [https://console.groq.com/keys](url) is being flagged incorrectly as a broken link by the tests, perhaps because it requires login to access.

**Comment by dloman118** [comment]
> thanks @dloman118 for the updates! can you pls use `<!-- markdown-link-check-disable --> and <!-- markdown-link-check-enable -->` to bypass the error.

Thanks @HamidShojanazeri we should be all set with the broken links now. We are still failing the Spellcheck test with valid words like the following, are there additional strategies to ignore these in the tests or is this ok?

```
DataFrame
DuckDB
Groq
GroqCloud
Replit
Teslas
duckdb
teslas
```

**Review by HamidShojanazeri — APPROVED** [review]
Thanks for the updates, @dloman118! LGTM

**Pull request merged**
