### PR TITLE
[OctoAI] Introducing a Video Generation use case featuring Llama3

### PR DESCRIPTION
**Pull request by tmoreau89**
# What does this PR do?
This example under `lama-recipes/recipes/use_cases` demonstrates a "model cocktail" of Llama3, image generation and image animation to produce a full recipe video based on a simple text prompt - the name of the dish.

In particular this demo shows how one can use Llama3's JSON formatting capabilities to generate a scene by scene description of a recipe making video.

This demo is powered by OctoAI as the model API provider but the user can feel free to choose whichever model API provider they'd like.

## Feature/Issue validation/testing

This demo was run on Jupyter notebook on a Macbook M1 machine and in Google Colab (T4-based).

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/facebookresearch/llama-recipes/blob/main/CONTRIBUTING.md#pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes?  
- [ ] Did you write any new necessary tests?

Thanks for contributing 🎉!

### CODE REVIEW

**Comment by tmoreau89** [comment]
CC @HamidShojanazeri

**Comment by tmoreau89** [comment]
Hey @HamidShojanazeri ! It seems the linter errors are unrelated to the PR changes. Do you have a recommendation here? Thanks!

**Comment by tmoreau89** [comment]
Looks like after all we're all green!

**Review by HamidShojanazeri — APPROVED** [review]

**Comment by tmoreau89** [comment]
Thanks for merging @HamidShojanazeri !

**Pull request merged**
