### PR TITLE
added a notebook tutorial on llama 3.2 new capabilities

### PR DESCRIPTION
**Pull request by Monireh2**
# What does this PR do?

This pull request (PR) adds a new notebook tutorial that showcases the latest capabilities of LLaMA 3.2.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/facebookresearch/llama-recipes/blob/main/CONTRIBUTING.md#pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes?  
- [ ] Did you write any new necessary tests?

Thanks for contributing 🎉!

### CODE REVIEW

**Review by init27 — APPROVED** [review]

**Comment by init27** [comment]
@Monireh2 Thanks for the PR-this is awesome! 

Can you please add a Colab link in the readme and then merge?

**Comment by varunfb** [comment]
Please remove the QR codes from the images directory and make sure you remove the ack and thank you sections. These are meant for external talks only. Thanks

**Comment by Monireh2** [comment]
> @Monireh2 Thanks for the PR-this is awesome!
> 
> Can you please add a Colab link in the readme and then merge?

Thanks @init27! Updated the colab link!

**Comment by Monireh2** [comment]
> Please remove the QR codes from the images directory and make sure you remove the ack and thank you sections. These are meant for external talks only. Thanks

Thank @varunfb! Removed unnecessary images, had removed ack and thank you section!

**Pull request merged**
